#!/usr/bin/env python3

import sys
import argparse
import subprocess
import re

assert sys.version_info >= (3, 9), "Python 3.9 or later required to run this script."

"""The minimum `rtla --version` (aka kernel version?) that supports `timerlat_print_stats_all()`.
This was introduced in commit 1462501c7a8d565f5949d3d5635b2111d889aaaa.
GitHub link: https://github.com/torvalds/linux/commit/1462501c7a8d565f5949d3d5635b2111d889aaaa
The GitHub link shows us tags associated with this commit, where we see 6.10.0 as the first version
including it.
"""
MIN_RTLA_SUMMARY_VERSION = (6, 10, 0)


def parse_args() -> tuple[argparse.Namespace, list[str]]:
    """Parse CLI arguments.
    Any unknown arguments are collected to be passed to rtla itself.
    """

    rtla_help_text = subprocess.run(
        ["rtla", "timerlat", "hist", "--help"], capture_output=True
    ).stderr.decode()

    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter, epilog=rtla_help_text
    )
    parser.add_argument("-d", "--duration", required=True, help=argparse.SUPPRESS)
    # WARNING: This overlaps with RTLA's debug flag!
    parser.add_argument("--debug", action="store_true", help="Print debug output.")
    return parser.parse_known_args()


def main():
    args, unknown_args = parse_args()
    cmd = f"rtla timerlat hist --duration {args.duration} {' '.join(unknown_args)}"
    try:
        result = subprocess.run(cmd.split(), capture_output=True, check=True)

        # HACK: RTLA doesn't EXIT_FAILURE if you specify an unknown argument.
        if b"unrecognized option" in result.stderr:
            raise subprocess.CalledProcessError(
                returncode=1,
                cmd=cmd,
                output=result.stdout,
                stderr=result.stderr,
            )

    except subprocess.CalledProcessError as e:
        print(e.stderr.decode(), file=sys.stderr)
        sys.exit(e.returncode)

    # Extract relevant result data.
    stdout = result.stdout.decode()

    if args.debug:
        pad = 100
        print(pad * "=")
        print(f"rtla timerlat stdout (size: {sys.getsizeof(stdout)}b)")
        print(pad * "=")
        print(stdout)
        print(pad * "=")
        print("rtla timerlat stderr")
        print(pad * "=")
        print(result.stderr.decode())
        print(pad * "=")

    if does_rtla_version_support_summary():
        parse_summary(stdout)
    else:
        if args.debug:
            print("Old version of rtla, parsing the output ourselves...")
        pass


def does_rtla_version_support_summary() -> bool:
    """
    Check if the version of RTLA is the minimum version which supports
    printing a summary at the end of the test.

    For versions < 6.10 (what we have in Jammy circa April 2025), we have to do this ourselves.
    """
    cmd = "rtla --version"
    stdout = subprocess.run(cmd.split(), capture_output=True).stderr.decode()

    version_pattern = r"\d+\.\d+\.\d+"
    try:
        version_str = re.search(version_pattern, stdout).group()
    except AttributeError:
        print("Error: `rtla --version` printed something unexpected.", file=sys.stderr)
        sys.exit(1)

    version = tuple(int(i) for i in version_str.split("."))
    return version >= MIN_RTLA_SUMMARY_VERSION


def parse_summary(stdout: str):
    combined_results_section = stdout[stdout.find("ALL:") :]
    results = [
        [
            words
            for words in line.split()[1:]  # Delete first column, which is just a label
        ]
        for line in combined_results_section.splitlines()[1:]  # Delete first row
    ]

    # This should be a 4x3 matrix.
    assert len(results) == 4
    for i in range(4):
        assert len(results[i]) == 3

    # NOTE: If you remove elements from the lists, be sure to adjust the index accordingly.
    for col, colname in enumerate(["IRQ", "Thr", "Usr"]):
        for row, rowname in enumerate(["count", "min", "average", "max"]):
            print(f"rtla_timerlat__{colname}_{rowname}", results[row][col])


if __name__ == "__main__":
    main()
