#!/usr/bin/env python3

import sys
import argparse
import subprocess
import re
import itertools

assert sys.version_info >= (3, 9), "Python 3.9 or later required to run this script."

"""The minimum `rtla --version` (aka kernel version?) that supports `timerlat_print_stats_all()`.
This was introduced in commit 1462501c7a8d565f5949d3d5635b2111d889aaaa.
GitHub link: https://github.com/torvalds/linux/commit/1462501c7a8d565f5949d3d5635b2111d889aaaa
The GitHub link shows us tags associated with this commit, where we see 6.10.0 as the first version
including it.
"""
MIN_RTLA_SUMMARY_VERSION = (6, 10, 0)


def parse_args() -> tuple[argparse.Namespace, list[str]]:
    """Parse CLI arguments.
    Any unknown arguments are collected to be passed to rtla itself.
    """

    rtla_help_text = subprocess.run(
        ["rtla", "timerlat", "hist", "--help"], capture_output=True
    ).stderr.decode()

    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter, epilog=rtla_help_text
    )
    parser.add_argument("-d", "--duration", required=True, help=argparse.SUPPRESS)
    # WARNING: This overlaps with RTLA's debug flag!
    parser.add_argument("--debug", action="store_true", help="Print debug output.")
    return parser.parse_known_args()


def main():
    args, unknown_args = parse_args()
    cmd = f"rtla timerlat hist --duration {args.duration} {' '.join(unknown_args)}"
    try:
        result = subprocess.run(cmd.split(), capture_output=True, check=True)

        # HACK: RTLA doesn't EXIT_FAILURE if you specify an unknown argument.
        if b"unrecognized option" in result.stderr:
            raise subprocess.CalledProcessError(
                returncode=1,
                cmd=cmd,
                output=result.stdout,
                stderr=result.stderr,
            )

    except subprocess.CalledProcessError as e:
        print(e.stderr.decode(), file=sys.stderr)
        sys.exit(e.returncode)

    # Extract relevant result data.
    stdout = result.stdout.decode()

    if args.debug:
        pad = 100
        print(pad * "=")
        print(f"rtla timerlat stdout (size: {sys.getsizeof(stdout)}b)")
        print(pad * "=")
        print(stdout)
        print(pad * "=")
        print("rtla timerlat stderr")
        print(pad * "=")
        print(result.stderr.decode())
        print(pad * "=")

    if does_rtla_version_support_summary():
        parse_summary(stdout)
    else:
        if args.debug:
            print("Old version of rtla, parsing the output ourselves...")
        timerlat_print_stats_all(stdout, args.debug)


def does_rtla_version_support_summary() -> bool:
    """
    Check if the version of RTLA is the minimum version which supports
    printing a summary at the end of the test.

    For versions < 6.10 (what we have in Jammy circa April 2025), we have to do this ourselves.
    """
    cmd = "rtla --version"
    stdout = subprocess.run(cmd.split(), capture_output=True).stderr.decode()

    version_pattern = r"\d+\.\d+\.\d+"
    try:
        version_str = re.search(version_pattern, stdout).group()
    except AttributeError:
        print("Error: `rtla --version` printed something unexpected.", file=sys.stderr)
        sys.exit(1)

    version = tuple(int(i) for i in version_str.split("."))
    return version >= MIN_RTLA_SUMMARY_VERSION


def parse_summary(stdout: str):
    combined_results_section = stdout[stdout.find("ALL:") :]
    results = [
        [
            words
            for words in line.split()[1:]  # Delete first column, which is just a label
        ]
        for line in combined_results_section.splitlines()[1:]  # Delete first row
    ]

    # This should be a 4x3 matrix.
    assert len(results) == 4
    for i in range(4):
        assert len(results[i]) == 3

    # NOTE: If you remove elements from the lists, be sure to adjust the index accordingly.
    for col, colname in enumerate(["IRQ", "Thr", "Usr"]):
        for row, rowname in enumerate(["count", "min", "average", "max"]):
            print(f"rtla_timerlat__{colname}_{rowname}", results[row][col])


def timerlat_print_stats_all(stdout: str, debug: bool):
    """
    This is a simplified port of the function by the same name in the Linux kernel.
    See the above docs on MIN_RTLA_SUMMARY_VERSION for more info.
    """
    lines = stdout.splitlines()

    # Sample (of the subset of output we need):
    # RTLA timerlat histogram
    # ...
    # Index   IRQ-000   Thr-000   IRQ-001   Thr-001   IRQ-002   Thr-002   IRQ-003   Thr-003   IRQ-004   Thr-004   IRQ-005   Thr-005   IRQ-006   Thr-006   IRQ-007   Thr-007   IRQ-008   Thr-008   IRQ-009   Thr-009   IRQ-010   Thr-010   IRQ-011   Thr-011
    # ...
    # over:       232       357       233       363       237       353       318       437       362       481       377       483       280       376       236       305       235       312       240       313       241       314       239       316
    # count:   600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007
    # min:          0         3         0         4         0         4         0         4         1         4         1         6         1         3         1         3         1         3         1         3         1         3         1         4
    # avg:          2        12         2        12         2        13        14        25        16        28        16        28         2        10         2         9         3        10         3        10         3        10         3        10
    # max:        484       499       431       453       399       416       374       389       351       381       354       370       336       346       404       419       386       395       364       373       334       343       342       352

    # NOTE: new versions seem to also include Usr... when did that get added?

    # Get the indices
    index_line = lines[3]
    assert index_line.startswith("Index")

    index_words = index_line.split()  # IRQ-000, ..., IRQ-n
    assert len(index_words) >= 2
    for i, e in enumerate(index_words):
        if e.endswith("-001"):
            break
    categories = [s[: s.find("-")] for s in index_words[1:i]]  # pyright: ignore [reportPossiblyUnboundVariable] (we verify this above)

    if debug:
        print(f"{categories=}")

    def find_line(key: str) -> str:
        return next(line for line in lines if line.startswith(key))

    def parse_line(key: str) -> list[int]:
        return [int(word) for word in find_line(key).split()[1:]]

    # TODO do the same for the others. Then, convert to list[int]. Then, do the math. Then print. Then smile because you're done.
    all_counts = parse_line("count:")
    all_mins = parse_line("min:")
    all_avgs = parse_line("avg:")  # TODO this is rounded (float division)
    all_maxs = parse_line("max:")

    results = {stat: dict.fromkeys(categories, []) for stat in ["count", "min", "avg", "max"]}

    # Batch the min by category
    def populate_results(statistic: str, all_data: list[int]):
        for mins_batch in itertools.batched(all_data, len(categories)):
            for category, data in zip(categories, mins_batch):
                results[statistic][category].append(data)

    populate_results("count", all_counts)
    populate_results("min", all_mins)
    populate_results("avg", all_avgs)
    populate_results("max", all_maxs)

    # Do the math, print the result
    for category in categories:
        for statistic in results.keys():
            if statistic == "count":
                print(f"rtla_timerlat__{category}_{statistic}", sum(results[statistic][category]))
            elif statistic == "min":
                print(f"rtla_timerlat__{category}_{statistic}", min(results[statistic][category]))
            elif statistic == "avg":
                data = results["avg"][category]
                avg = round(sum(data) / len(data))  # NOTE: Uses banker's rounding, so 0.5 -> 0.0
                print(f"rtla_timerlat__{category}_average", avg)
            elif statistic == "max":
                print(f"rtla_timerlat__{category}_{statistic}", max(results[statistic][category]))


if __name__ == "__main__":
    main()
