#!/usr/bin/env python3

import sys
import argparse
import subprocess
import re
import platform
import itertools

assert sys.version_info >= (3, 9), "Python 3.9 or later required to run this script."

"""The minimum `rtla --version` (aka kernel version?) that supports `timerlat_print_stats_all()`.
This was introduced in commit 1462501c7a8d565f5949d3d5635b2111d889aaaa.
GitHub link: https://github.com/torvalds/linux/commit/1462501c7a8d565f5949d3d5635b2111d889aaaa
The GitHub link shows us tags associated with this commit, where we see 6.10.0 as the first version
including it.
"""
MIN_RTLA_SUMMARY_VERSION = (6, 10, 0)


def print_debuginfo():
    pad = 100
    print(pad * "=")
    print("DEBUG INFO")
    print(pad * "=")

    def print_and_run(cmd: str):
        print(cmd)
        subprocess.run(cmd.split())

    print_and_run(f"git hash-object {__file__}")
    print(f"{sys.version=}")
    print_and_run("rtla --version")
    print_and_run("uname -a")
    print_and_run("lsb_release -a")

    print(pad * "=")


def setup_and_run_tuning():
    """Install and run cpupower, and use sysctl to tweak realtime settings."""
    flavor = re.split(r"-\d*-", platform.uname().release)[-1]
    cmd = f"apt-get install --yes linux-tools-{flavor}"
    try:
        subprocess.run(cmd.split(), check=True)
    except subprocess.CalledProcessError:
        print(f"Error installing linux-tools-{flavor}.", file=sys.stderr)
        return

    # Set performance governor (only on x86_64 for now)
    arch = platform.machine()
    if arch == 'x86_64':
        cmd = "cpupower frequency-set --governor performance"
        try:
            subprocess.run(cmd.split(), check=True)
        except subprocess.CalledProcessError:
            print("Error running cpupower.", file=sys.stderr)
            return

    cmd = "sysctl -w kernel.sched_rt_runtime_us=-1"
    try:
        subprocess.run(cmd.split(), check=True)
    except subprocess.CalledProcessError:
        print(f"Error running `{cmd}`.", file=sys.stderr)
        return


def parse_args() -> tuple[argparse.Namespace, list[str]]:
    """Parse CLI arguments.
    Any unknown arguments are collected to be passed to rtla itself.
    """

    rtla_help_text = subprocess.run(
        ["rtla", "timerlat", "hist", "--help"], capture_output=True
    ).stderr.decode()

    parser = argparse.ArgumentParser(
        formatter_class=argparse.RawDescriptionHelpFormatter, epilog=rtla_help_text
    )
    parser.add_argument("-d", "--duration", required=True, help=argparse.SUPPRESS)
    parser.add_argument("--verbose", action="store_true", help="Print verbose output.")
    return parser.parse_known_args()


def main():
    args, unknown_args = parse_args()

    if args.verbose:
        print_debuginfo()

    setup_and_run_tuning()

    cmd = f"rtla timerlat hist --duration {args.duration} {' '.join(unknown_args)}"
    try:
        result = subprocess.run(cmd.split(), capture_output=True, check=True)

        # HACK: RTLA doesn't EXIT_FAILURE if you specify an unknown argument.
        if b"unrecognized option" in result.stderr:
            raise subprocess.CalledProcessError(
                returncode=1,
                cmd=cmd,
                output=result.stdout,
                stderr=result.stderr,
            )

    except subprocess.CalledProcessError as e:
        print(e.stderr.decode(), file=sys.stderr)
        sys.exit(e.returncode)

    # Extract relevant result data.
    stdout = result.stdout.decode()

    if args.verbose:
        pad = 100
        print(pad * "=")
        print(f"rtla timerlat stdout (size: {sys.getsizeof(stdout)}b)")
        print(pad * "=")
        print(stdout)
        print(pad * "=")
        print(f"rtla timerlat stderr {'<EMPTY>' if len(result.stderr) == 0 else ''}")
        print(pad * "=")
        print(result.stderr.decode())
        print(pad * "=")

    if does_rtla_version_support_summary(args.verbose):
        parse_summary(stdout)
    else:
        timerlat_print_stats_all(stdout, args.verbose)


def does_rtla_version_support_summary(verbose: bool) -> bool:
    """
    Check if the version of RTLA is the minimum version which supports
    printing a summary at the end of the test.

    For versions < 6.10 (what we have in Jammy circa April 2025), we have to do this ourselves.
    """
    cmd = "rtla --version"
    stdout = subprocess.run(cmd.split(), capture_output=True).stderr.decode()

    version_pattern = r"\d+\.\d+\.\d+"
    try:
        version_str = re.search(version_pattern, stdout).group()
    except AttributeError:
        print("Error: `rtla --version` printed something unexpected.", file=sys.stderr)
        sys.exit(1)

    version = tuple(int(i) for i in version_str.split("."))
    if verbose:
        print("RTLA version (parsed tuple):", version)
    return version >= MIN_RTLA_SUMMARY_VERSION


def parse_summary(stdout: str):
    combined_results_section = stdout[stdout.find("ALL:") :]
    results = {
        line.split()[0].removesuffix(":"): line.split()[1:]
        for line in combined_results_section.splitlines()
    }

    # This should be a 4x3 matrix.
    assert len(results) == 5
    for k in results.keys():
        assert len(results[k]) == len(results["ALL"])

    for i, colname in enumerate(results["ALL"]):
        for rowname in ["min", "avg", "max"]:  # NOTE: skip "count"
            value = results[rowname][i]
            # HACK: We need to print "average", not "avg", to trigger influxdb.
            if rowname == "avg":
                rowname = "average"
            print(f"rtla_timerlat__{colname}_{rowname}", value)


def timerlat_print_stats_all(stdout: str, verbose: bool):
    """
    This is a simplified port of the function by the same name in the Linux kernel.
    See the above docs on MIN_RTLA_SUMMARY_VERSION for more info.
    """
    lines = stdout.splitlines()

    # Sample (of the subset of output we need):
    # RTLA timerlat histogram
    # ...
    # Index   IRQ-000   Thr-000   IRQ-001   Thr-001   IRQ-002   Thr-002   IRQ-003   Thr-003   IRQ-004   Thr-004   IRQ-005   Thr-005   IRQ-006   Thr-006   IRQ-007   Thr-007   IRQ-008   Thr-008   IRQ-009   Thr-009   IRQ-010   Thr-010   IRQ-011   Thr-011
    # ...
    # over:       232       357       233       363       237       353       318       437       362       481       377       483       280       376       236       305       235       312       240       313       241       314       239       316
    # count:   600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007    600007
    # min:          0         3         0         4         0         4         0         4         1         4         1         6         1         3         1         3         1         3         1         3         1         3         1         4
    # avg:          2        12         2        12         2        13        14        25        16        28        16        28         2        10         2         9         3        10         3        10         3        10         3        10
    # max:        484       499       431       453       399       416       374       389       351       381       354       370       336       346       404       419       386       395       364       373       334       343       342       352

    # NOTE: new versions seem to also include Usr... when did that get added?

    # Get the indices
    index_line = lines[3]
    assert index_line.startswith("Index")

    index_words = index_line.split()  # IRQ-000, ..., IRQ-n
    assert len(index_words) >= 2
    for i, e in enumerate(index_words):
        if e.endswith("-001"):
            break
    categories = [s[: s.find("-")] for s in index_words[1:i]]  # pyright: ignore [reportPossiblyUnboundVariable] (we verify this above)

    if verbose:
        print(f"{categories=}")

    def find_line(key: str) -> str:
        return next(line for line in lines if line.startswith(key))

    def parse_line(key: str) -> list[int]:
        return [int(word) for word in find_line(key).split()[1:]]

    # TODO do the same for the others. Then, convert to list[int]. Then, do the math. Then print. Then smile because you're done.
    all_counts = parse_line("count:")
    all_mins = parse_line("min:")
    all_avgs = parse_line("avg:")  # TODO this is rounded (float division)
    all_maxs = parse_line("max:")

    results = {
        stat: {k: [] for k in categories} for stat in ["count", "min", "avg", "max"]
    }

    # Batch the min by category
    def populate_results(statistic: str, all_data: list[int]):
        for mins_batch in itertools.batched(all_data, len(categories)):
            for category, data in zip(categories, mins_batch):
                results[statistic][category].append(data)

    populate_results("count", all_counts)
    populate_results("min", all_mins)
    populate_results("avg", all_avgs)
    populate_results("max", all_maxs)

    # Do the math, print the result
    for category in categories:
        for statistic in results.keys():
            # if statistic == "count":
            #     print(f"rtla_timerlat__{category}_{statistic}", sum(results[statistic][category]))
            if statistic == "min":
                print(
                    f"rtla_timerlat__{category}_{statistic}",
                    min(results[statistic][category]),
                )
            elif statistic == "avg":
                data = results["avg"][category]
                avg = round(
                    sum(data) / len(data)
                )  # NOTE: Uses banker's rounding, so 0.5 -> 0.0
                print(f"rtla_timerlat__{category}_average", avg)
            elif statistic == "max":
                print(
                    f"rtla_timerlat__{category}_{statistic}",
                    max(results[statistic][category]),
                )


if __name__ == "__main__":
    main()
