language: python
python:
    - "2.7"
    - "2.6"

branches:
    only:
        - master

sudo: false

git:
    submodules: false

install:
    - pip install setuptools
    - pip install sphinx==1.4.9
    - AUTOTEST_TOP_PATH="." pip install -r requirements-selftests.txt

script:
    - ./runtests.py -c .nose.cfg
    - inspekt lint
