#!/bin/bash
#
# xlnx-config: Check the board configuration
#

function rt_test()
{
	board=$(xlnx-config --get-board)
	if [[ ${board} != ${RT_XILINX_BOARD} ]] ; then
		rt_fail "Device tree board does not match xlnx-config. ${board} != ${RT_XILINX_BOARD}"
	fi
}

root=$(cd "$(dirname "${BASH_SOURCE[0]}")"/.. && pwd)
# shellcheck disable=SC1090
. "${root}"/lib/run-test
