# kernel_taint_test known issues for module taint flags

dgx_modules = {'jammy':  {'nvidia_uvm':     'POE',
                          'nvidia_drm':     'POE',
                          'nvidia_modeset': 'POE',
                          'nvidia':         'POE',
                          'mlx5_ib':        'OE',
                          'ib_uverbs':      'OE',
                          'ib_core':        'OE',
                          'mlx5_core':      'OE',
                          'mlxdevm':        'OE',
                          'mlxfw':          'OE',
                          'mlx_compat':     'OE'},
               'focal':  {'nvidia_uvm':     'O',
                          'nvidia_drm':     'PO',
                          'nvidia_modeset': 'PO',
                          'nvidia':         'PO',
                          'mlx5_ib':        'OE',
                          'ib_uverbs':      'OE',
                          'ib_core':        'OE',
                          'mlx5_core':      'OE',
                          'mlxdevm':        'OE',
                          'auxiliary':      'OE',
                          'mlxfw':          'OE',
                          'mlx_compat':     'OE'},
               'bionic': {'nvidia_uvm':     'O',
                          'nvidia_drm':     'PO',
                          'nvidia_modeset': 'PO',
                          'nvidia':         'PO',
                          'ib_iser':        'OE',
                          'rdma_cm':        'OE',
                          'iw_cm':          'OE',
                          'ib_cm':          'OE',
                          'mlx5_ib':        'OE',
                          'ib_uverbs':      'OE',
                          'ib_core':        'OE',
                          'mlx5_core':      'OE',
                          'mlxfw':          'OE',
                          'mdev':           'OE',
                          'mlx_compat':     'OE'}}

rpi_modules = {'all': {'snd_bcm2835':        'CE',
                       'rpivid_hevc':        'CE',
                       'bcm2835_codec':      'CE',
                       'bcm2835_v4l2':       'CE',
                       'bcm2835_isp':        'CE',
                       'bcm2835_mmal_vchiq': 'CE',
                       'vc_sm_cma':          'CE'}}
